package com.carbonmarket.service;

import com.carbonmarket.domain.Agreement;
import com.carbonmarket.domain.Co2Passport;
import com.carbonmarket.domain.Company;
import com.carbonmarket.domain.SaleMode;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.UUID;

/** Auto-generated draft contract (Markdown) from an agreement's terms. */
@Service
public class ContractDocumentService {
    private final Lookup lookup;
    private final AgreementService agreementService;

    public ContractDocumentService(Lookup lookup, AgreementService agreementService) {
        this.lookup = lookup;
        this.agreementService = agreementService;
    }

    @Transactional(readOnly = true)
    public String markdown(UUID agreementId) {
        Agreement a = lookup.agreement(agreementId);
        agreementService.assertCanView(a);
        Company e = lookup.company(a.getEmitterId());
        Company u = lookup.company(a.getUtilizerId());
        Co2Passport p = lookup.passport(a.getPassportId());
        double total = a.getVolumeTonnes() * a.getPricePerTonne();
        double deposit = a.getDepositPct() == null ? 0 : total * a.getDepositPct() / 100.0;
        String kind = switch (a.getMode()) {
            case CONTRACT -> "LONG-TERM CO2 SUPPLY CONTRACT";
            case AUCTION -> "SPOT CO2 SALE AGREEMENT (AUCTION)";
            case TENDER -> "CO2 SUPPLY AGREEMENT (TENDER / RFQ)";
        };
        StringBuilder sb = new StringBuilder();
        sb.append("# ").append(kind).append("\n\n");
        sb.append("**Draft generated by the Carbon Marketplace on ").append(LocalDate.now()).append("** — Agreement ref `").append(a.getId()).append("` · Status: ").append(a.getStatus()).append("\n\n");
        sb.append("## 1. Parties\n\n");
        sb.append("- **Supplier (Emitter):** ").append(e.getName()).append(", ").append(addr(e)).append("\n");
        sb.append("- **Buyer (Utilizer):** ").append(u.getName()).append(", ").append(addr(u)).append("\n\n");
        sb.append("## 2. Subject: CO2 Passport ").append(p.getPassportCode()).append("\n\n");
        sb.append("| Field | Value |\n|---|---|\n");
        row(sb, "Source", p.getSource()); row(sb, "Carbon origin", p.getCarbonOrigin()); row(sb, "Capture technology", p.getCaptureTechnology());
        row(sb, "CO2 concentration", p.getConcentrationPct() + " %"); row(sb, "State", p.getPhysicalState());
        row(sb, "Pressure / Temperature", p.getPressureBar() + " bar / " + p.getTemperatureC() + " °C");
        row(sb, "Impurities (ppm)", p.getImpurities()); row(sb, "Lab certificate", p.getLabCertificateStatus() + " (" + lookup.companyName(p.getIssuingLabId()) + ", expires " + p.getCoaExpiresAt() + ")");
        row(sb, "Meter ID", p.getMeterId()); row(sb, "Location", p.getLocationName());
        sb.append("\n## 3. Volume & Delivery Schedule\n\n");
        if (a.getMode() == SaleMode.CONTRACT) {
            sb.append(String.format("- Recurring delivery of **%.1f t per month** for **%d months** (total **%.1f t**), starting %s and ending %s.\n",
                    a.getVolumePerMonth(), a.getDurationMonths(), a.getVolumeTonnes(), a.getStartsAt(), a.getEndsAt()));
            sb.append(a.isTakeOrPay()
                    ? "- **Take-or-pay:** the Buyer pays for the monthly committed volume whether or not it is drawn.\n"
                    : "- No take-or-pay clause: the Buyer pays only for delivered volume.\n");
        } else {
            sb.append(String.format("- One-off supply of **%.1f t** within the delivery window %s to %s, in one or more shipments.\n",
                    a.getVolumeTonnes(), a.getStartsAt(), a.getEndsAt()));
        }
        sb.append("- The committed volume is locked on the Passport's allocation ledger and cannot be resold by the Supplier.\n\n");
        sb.append("## 4. Pricing\n\n");
        sb.append(String.format("- **₹%.2f per tonne**, %s", a.getPricePerTonne(), a.getPricingStructure() == null ? "fixed" : a.getPricingStructure() == com.carbonmarket.domain.PricingStructure.FIXED ? "fixed for the full duration." : "indexed to the platform cost formula (base + purification + transport + verification), re-computed monthly."));
        sb.append(String.format("\n- Indicative contract value: **₹%,.0f**.\n", total));
        sb.append("- Purification, transport and verification are charged per the platform Cost Stack shown to the Buyer at the time of the offer; each layer is itemised on every invoice.\n\n");
        sb.append("## 5. Service Level (SLA)\n\n");
        sb.append(String.format("- Acceptable supply gap: **%.1f %%** of the committed volume per period. Beyond this the Supplier owes a penalty equal to the price difference for replacement supply sourced through the marketplace backup-matching service.\n",
                a.getSupplyGapThresholdPct() == null ? 10.0 : a.getSupplyGapThresholdPct()));
        sb.append("- The Supplier must post output forecasts for planned maintenance at least 14 days ahead; the platform notifies the Buyer and suggests alternatives.\n\n");
        sb.append("## 6. Deposit / Escrow\n\n");
        sb.append(String.format("- Deposit of **%.1f %%** (₹%,.0f) held at signing. Forfeited, and the cancelling party's trust tier penalised, if the agreement is broken before %s.\n\n",
                a.getDepositPct() == null ? 0 : a.getDepositPct(), deposit, a.getEndsAt()));
        sb.append("## 7. Verification & Chain of Custody\n\n");
        sb.append("- Every shipment: point-of-loading sample + numbered tamper-evident seal, signed meter reading; point-of-delivery re-sample, seal check and weight reconciliation within a 2 % leakage tolerance. Mismatches are auto-flagged to both parties and the lab.\n");
        sb.append("- The Supplier's COA must remain valid (re-tested every 6 months); an expired COA suspends new shipments.\n\n");
        sb.append("## 8. Renewal\n\n");
        sb.append("- Either party may open a renewal negotiation from the platform within 60 days of the end date, pre-filled with these terms.\n\n");
        sb.append("## 9. Signatures\n\n");
        sb.append("| For the Supplier | For the Buyer |\n|---|---|\n| ").append(e.getName()).append(" | ").append(u.getName()).append(" |\n| Name / Title: ____________ | Name / Title: ____________ |\n| Date: ____________ | Date: ____________ |\n\n");
        sb.append("_This draft is generated deterministically from the agreement record and is not legal advice._\n");
        return sb.toString();
    }

    private static String addr(Company c) {
        return (c.getAddress() == null ? "" : c.getAddress() + ", ") + c.getCity() + ", " + c.getState() + (c.getRegistrationNumber() == null ? "" : " (Reg. " + c.getRegistrationNumber() + ")");
    }

    private static void row(StringBuilder sb, String k, Object v) { sb.append("| ").append(k).append(" | ").append(v == null ? "—" : v).append(" |\n"); }
}
